// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt@3.16.2_@netlify+blobs@8.2.0_@parcel+watcher@2.5.1_@types+node@18.19.86_db0@0.3.1_e_d6acea6cf18e03b5b1756bcd3e3e44c5/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}